//! Stealth System: sneaking, detection mechanics, backstab bonuses, and noise levels
//!
//! This module provides a comprehensive stealth system for the ShadowCrypt roguelike,
//! enabling tactical gameplay through sneaking, enemy awareness, and surprise attacks.
//!
//! # Features
//!
//! - **Sneaking**: Players can enter stealth mode to avoid detection
//! - **Detection**: Enemies have awareness levels and detection ranges
//! - **Noise**: Actions generate noise that can alert enemies
//! - **Backstab**: Attacking unaware enemies deals bonus damage
//! - **Environmental Factors**: Terrain and lighting affect stealth

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

use crate::combat::StatusEffect;
use crate::entities::EnemyKind;
use crate::world::Tile;

/// Light level affecting visibility and stealth
#[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Debug, Default)]
pub enum LightLevel {
    /// Complete darkness - excellent for stealth
    Dark,
    /// Dim lighting - good for stealth
    Dim,
    /// Normal dungeon lighting
    #[default]
    Normal,
    /// Bright lighting - poor for stealth
    Bright,
}

impl LightLevel {
    /// Returns the stealth modifier for this light level
    /// Higher values make stealth easier (reduce detection chance)
    pub fn stealth_modifier(&self) -> f32 {
        match self {
            Self::Dark => 0.4,   // 60% harder to detect
            Self::Dim => 0.7,    // 30% harder to detect
            Self::Normal => 1.0, // No modifier
            Self::Bright => 1.5, // 50% easier to detect
        }
    }

    /// Returns a color index for UI rendering
    pub fn color_index(&self) -> u8 {
        match self {
            Self::Dark => 0,    // DarkGrey
            Self::Dim => 1,     // Grey
            Self::Normal => 2,  // White
            Self::Bright => 11, // Yellow
        }
    }

    /// Returns the display name
    pub fn name(&self) -> &'static str {
        match self {
            Self::Dark => "Dark",
            Self::Dim => "Dim",
            Self::Normal => "Normal",
            Self::Bright => "Bright",
        }
    }
}

/// Noise level generated by various actions
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Debug)]
pub enum NoiseLevel {
    /// Silent - no noise generated
    Silent = 0,
    /// Whisper - very quiet, minimal detection range
    Whisper = 1,
    /// Quiet - slight noise, small detection range
    Quiet = 2,
    /// Normal - standard movement noise
    Normal = 3,
    /// Loud - significant noise, alerts nearby enemies
    Loud = 4,
    /// Deafening - extreme noise, alerts enemies in large radius
    Deafening = 5,
}

impl NoiseLevel {
    /// Returns the detection radius this noise level propagates to
    pub fn detection_radius(&self) -> u32 {
        match self {
            Self::Silent => 0,
            Self::Whisper => 1,
            Self::Quiet => 3,
            Self::Normal => 5,
            Self::Loud => 8,
            Self::Deafening => 15,
        }
    }

    /// Returns the display name
    pub fn name(&self) -> &'static str {
        match self {
            Self::Silent => "Silent",
            Self::Whisper => "Whisper",
            Self::Quiet => "Quiet",
            Self::Normal => "Normal",
            Self::Loud => "Loud",
            Self::Deafening => "Deafening",
        }
    }

    /// Returns a color index for UI rendering
    pub fn color_index(&self) -> u8 {
        match self {
            Self::Silent => 0,    // DarkGrey
            Self::Whisper => 1,   // Grey
            Self::Quiet => 5,     // Green
            Self::Normal => 11,   // Yellow
            Self::Loud => 3,      // Red
            Self::Deafening => 4, // DarkRed
        }
    }
}

/// Actions that generate noise
#[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Debug)]
pub enum NoisyAction {
    /// Normal walking
    Walk,
    /// Sneaking movement
    Sneak,
    /// Running/sprinting
    Run,
    /// Melee attack
    MeleeAttack,
    /// Ranged attack
    RangedAttack,
    /// Casting a spell
    CastSpell,
    /// Opening a door
    OpenDoor,
    /// Opening a chest
    OpenChest,
    /// Drinking a potion
    DrinkPotion,
    /// Dropping an item
    DropItem,
    /// Using stairs
    UseStairs,
    /// Combat (enemy dying, etc)
    Combat,
    /// Triggering a trap
    TriggerTrap,
    /// Breaking something
    Break,
}

impl NoisyAction {
    /// Returns the base noise level for this action
    pub fn base_noise(&self) -> NoiseLevel {
        match self {
            Self::Sneak => NoiseLevel::Silent,
            Self::Walk => NoiseLevel::Quiet,
            Self::Run => NoiseLevel::Normal,
            Self::RangedAttack => NoiseLevel::Quiet,
            Self::DrinkPotion => NoiseLevel::Whisper,
            Self::DropItem => NoiseLevel::Whisper,
            Self::MeleeAttack => NoiseLevel::Normal,
            Self::CastSpell => NoiseLevel::Normal,
            Self::OpenDoor => NoiseLevel::Normal,
            Self::OpenChest => NoiseLevel::Normal,
            Self::UseStairs => NoiseLevel::Normal,
            Self::Combat => NoiseLevel::Loud,
            Self::TriggerTrap => NoiseLevel::Loud,
            Self::Break => NoiseLevel::Deafening,
        }
    }

    /// Returns the display name
    pub fn name(&self) -> &'static str {
        match self {
            Self::Walk => "Walking",
            Self::Sneak => "Sneaking",
            Self::Run => "Running",
            Self::MeleeAttack => "Melee Attack",
            Self::RangedAttack => "Ranged Attack",
            Self::CastSpell => "Casting Spell",
            Self::OpenDoor => "Opening Door",
            Self::OpenChest => "Opening Chest",
            Self::DrinkPotion => "Drinking Potion",
            Self::DropItem => "Dropping Item",
            Self::UseStairs => "Using Stairs",
            Self::Combat => "Combat",
            Self::TriggerTrap => "Triggering Trap",
            Self::Break => "Breaking",
        }
    }
}

/// Enemy awareness state
#[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Debug, Default)]
pub enum AwarenessState {
    /// Enemy is completely unaware of the player
    #[default]
    Unaware,
    /// Enemy heard something suspicious
    Suspicious,
    /// Enemy is searching for something
    Searching,
    /// Enemy is alert and actively looking
    Alert,
    /// Enemy has spotted the player
    Aware,
    /// Enemy is in active combat
    Combat,
}

impl AwarenessState {
    /// Returns the display name
    pub fn name(&self) -> &'static str {
        match self {
            Self::Unaware => "Unaware",
            Self::Suspicious => "Suspicious",
            Self::Searching => "Searching",
            Self::Alert => "Alert",
            Self::Aware => "Aware",
            Self::Combat => "Combat",
        }
    }

    /// Returns a color index for UI rendering
    pub fn color_index(&self) -> u8 {
        match self {
            Self::Unaware => 1,    // Grey
            Self::Suspicious => 11, // Yellow
            Self::Searching => 12,  // DarkYellow
            Self::Alert => 3,       // Red
            Self::Aware => 4,       // DarkRed
            Self::Combat => 3,      // Red
        }
    }

    /// Returns whether the enemy can perform backstab detection
    pub fn can_be_backstabbed(&self) -> bool {
        matches!(self, Self::Unaware | Self::Suspicious)
    }

    /// Returns the detection range modifier
    /// Lower values reduce enemy detection range
    pub fn detection_modifier(&self) -> f32 {
        match self {
            Self::Unaware => 0.5,
            Self::Suspicious => 0.75,
            Self::Searching => 1.0,
            Self::Alert => 1.25,
            Self::Aware => 1.5,
            Self::Combat => 1.5,
        }
    }

    /// Returns the next awareness state when detecting noise
    pub fn on_noise_detected(&self) -> Self {
        match self {
            Self::Unaware => Self::Suspicious,
            Self::Suspicious => Self::Searching,
            Self::Searching => Self::Alert,
            Self::Alert => Self::Alert,
            Self::Aware => Self::Aware,
            Self::Combat => Self::Combat,
        }
    }

    /// Returns the next awareness state on visual detection
    pub fn on_visual_detection(&self) -> Self {
        Self::Aware
    }

    /// Returns the state to decay to over time
    pub fn decay(&self) -> Self {
        match self {
            Self::Combat => Self::Alert,
            Self::Aware => Self::Alert,
            Self::Alert => Self::Searching,
            Self::Searching => Self::Suspicious,
            Self::Suspicious => Self::Unaware,
            Self::Unaware => Self::Unaware,
        }
    }
}

/// Backstab damage multiplier tiers
#[derive(Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Debug)]
pub enum BackstabTier {
    /// No backstab - enemy is aware
    None,
    /// Minor backstab - enemy is suspicious
    Minor,
    /// Standard backstab - enemy is unaware
    Standard,
    /// Critical backstab - perfect conditions
    Critical,
    /// Assassinate - instant kill on weak enemies
    Assassinate,
}

impl BackstabTier {
    /// Returns the damage multiplier for this backstab tier
    pub fn damage_multiplier(&self) -> f32 {
        match self {
            Self::None => 1.0,
            Self::Minor => 1.5,
            Self::Standard => 2.0,
            Self::Critical => 3.0,
            Self::Assassinate => 10.0,
        }
    }

    /// Returns the display name
    pub fn name(&self) -> &'static str {
        match self {
            Self::None => "Normal Attack",
            Self::Minor => "Sneak Attack",
            Self::Standard => "Backstab",
            Self::Critical => "Critical Backstab",
            Self::Assassinate => "Assassinate",
        }
    }

    /// Returns a color index for UI rendering
    pub fn color_index(&self) -> u8 {
        match self {
            Self::None => 2,       // White
            Self::Minor => 11,     // Yellow
            Self::Standard => 3,   // Red
            Self::Critical => 4,   // DarkRed
            Self::Assassinate => 13, // Magenta
        }
    }
}

/// Player stealth state tracking
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct StealthState {
    /// Whether the player is currently sneaking
    pub is_sneaking: bool,
    /// Base stealth skill (0-100)
    pub stealth_skill: u32,
    /// Current noise level generated
    pub current_noise: NoiseLevel,
    /// Turns spent in continuous stealth
    pub stealth_duration: u32,
    /// Last known light level at player position
    pub light_level: LightLevel,
    /// Bonus stealth from equipment/effects
    pub stealth_bonus: i32,
    /// Number of successful stealth kills
    pub stealth_kills: u32,
    /// Total backstab damage dealt
    pub backstab_damage_dealt: u64,
}

impl Default for StealthState {
    fn default() -> Self {
        Self::new()
    }
}

impl StealthState {
    /// Create a new stealth state
    pub fn new() -> Self {
        Self {
            is_sneaking: false,
            stealth_skill: 10,
            current_noise: NoiseLevel::Normal,
            stealth_duration: 0,
            light_level: LightLevel::Normal,
            stealth_bonus: 0,
            stealth_kills: 0,
            backstab_damage_dealt: 0,
        }
    }

    /// Create stealth state with a specific skill level
    pub fn with_skill(skill: u32) -> Self {
        Self {
            stealth_skill: skill.min(100),
            ..Self::new()
        }
    }

    /// Toggle sneaking mode
    pub fn toggle_sneak(&mut self) -> bool {
        self.is_sneaking = !self.is_sneaking;
        if self.is_sneaking {
            self.current_noise = NoiseLevel::Silent;
            self.stealth_duration = 0;
        } else {
            self.current_noise = NoiseLevel::Normal;
        }
        self.is_sneaking
    }

    /// Start sneaking
    pub fn start_sneak(&mut self) {
        self.is_sneaking = true;
        self.current_noise = NoiseLevel::Silent;
        self.stealth_duration = 0;
    }

    /// Stop sneaking
    pub fn stop_sneak(&mut self) {
        self.is_sneaking = false;
        self.current_noise = NoiseLevel::Normal;
    }

    /// Update stealth state each turn
    pub fn tick(&mut self) {
        if self.is_sneaking {
            self.stealth_duration += 1;
        }
    }

    /// Calculate effective stealth value (0-100+)
    pub fn effective_stealth(&self) -> i32 {
        let base = self.stealth_skill as i32;
        let sneak_bonus = if self.is_sneaking { 30 } else { 0 };
        let duration_bonus = (self.stealth_duration / 3).min(10) as i32;
        let light_mod = match self.light_level {
            LightLevel::Dark => 25,
            LightLevel::Dim => 10,
            LightLevel::Normal => 0,
            LightLevel::Bright => -20,
        };

        (base + sneak_bonus + duration_bonus + light_mod + self.stealth_bonus).max(0)
    }

    /// Calculate noise generated by an action
    pub fn calculate_noise(&self, action: NoisyAction) -> NoiseLevel {
        let base_noise = action.base_noise() as u8;

        // Sneaking reduces noise by 2 levels
        let sneak_reduction = if self.is_sneaking { 2 } else { 0 };

        // High stealth skill reduces noise
        let skill_reduction = (self.stealth_skill / 40) as u8; // 0-2 reduction

        let final_level = base_noise.saturating_sub(sneak_reduction + skill_reduction);

        match final_level {
            0 => NoiseLevel::Silent,
            1 => NoiseLevel::Whisper,
            2 => NoiseLevel::Quiet,
            3 => NoiseLevel::Normal,
            4 => NoiseLevel::Loud,
            _ => NoiseLevel::Deafening,
        }
    }

    /// Set the current noise level from an action
    pub fn make_noise(&mut self, action: NoisyAction) -> NoiseLevel {
        self.current_noise = self.calculate_noise(action);
        self.current_noise
    }

    /// Record a stealth kill
    pub fn record_stealth_kill(&mut self, damage: u32) {
        self.stealth_kills += 1;
        self.backstab_damage_dealt += damage as u64;
    }

    /// Increase stealth skill from practice
    pub fn gain_experience(&mut self, amount: u32) {
        self.stealth_skill = (self.stealth_skill + amount).min(100);
    }
}

/// Enemy detection and awareness tracking
#[derive(Clone, Serialize, Deserialize, Debug)]
pub struct EnemyAwareness {
    /// Current awareness state
    pub state: AwarenessState,
    /// Base perception skill (affects detection range)
    pub perception: u32,
    /// Turns until awareness decays
    pub decay_timer: u32,
    /// Last known player position (if any)
    pub last_known_position: Option<(usize, usize)>,
    /// Position being investigated
    pub investigation_point: Option<(usize, usize)>,
    /// Hearing range multiplier
    pub hearing_modifier: f32,
    /// Vision range multiplier
    pub vision_modifier: f32,
}

impl Default for EnemyAwareness {
    fn default() -> Self {
        Self::new(10)
    }
}

impl EnemyAwareness {
    /// Create new awareness with given perception
    pub fn new(perception: u32) -> Self {
        Self {
            state: AwarenessState::Unaware,
            perception,
            decay_timer: 0,
            last_known_position: None,
            investigation_point: None,
            hearing_modifier: 1.0,
            vision_modifier: 1.0,
        }
    }

    /// Create awareness for a specific enemy type
    pub fn for_enemy_kind(kind: EnemyKind) -> Self {
        let (perception, hearing, vision) = match kind {
            // Keen senses
            EnemyKind::Bat => (25, 2.0, 0.3),
            EnemyKind::Wolf | EnemyKind::DireWolf | EnemyKind::FrostWolf => (30, 1.5, 1.2),
            EnemyKind::Hellhound => (35, 1.5, 1.0),
            EnemyKind::ShadowAssassin => (40, 1.2, 1.5),

            // Poor senses
            EnemyKind::Zombie | EnemyKind::Mummy => (5, 0.5, 0.5),
            EnemyKind::Slime | EnemyKind::MagmaSlime => (3, 0.8, 0.2),
            EnemyKind::Golem | EnemyKind::BoneGolem | EnemyKind::LavaGolem => (8, 0.3, 1.0),
            EnemyKind::CursedStatue => (5, 0.1, 1.2),

            // Undead/spectral (detect life force)
            EnemyKind::Ghost | EnemyKind::Wraith | EnemyKind::IceWraith
            | EnemyKind::CinderWraith | EnemyKind::Banshee => (20, 0.5, 0.8),
            EnemyKind::Vampire | EnemyKind::VampireElite => (35, 1.3, 1.5),

            // Bosses have enhanced perception
            EnemyKind::BossGoblinKing => (25, 1.2, 1.2),
            EnemyKind::BossOrcWarlord => (30, 1.3, 1.3),
            EnemyKind::BossVampireLord => (45, 1.5, 1.5),
            EnemyKind::BossForestGuardian => (35, 1.5, 1.0),
            EnemyKind::BossIceDragon => (50, 1.3, 2.0),
            EnemyKind::BossDemonKing => (60, 1.5, 1.8),

            // Default moderate perception
            _ => (15, 1.0, 1.0),
        };

        Self {
            perception,
            hearing_modifier: hearing,
            vision_modifier: vision,
            ..Self::new(perception)
        }
    }

    /// Calculate effective detection range
    pub fn detection_range(&self) -> u32 {
        let base = 5 + (self.perception / 5);
        let state_mod = self.state.detection_modifier();
        ((base as f32) * state_mod * self.vision_modifier) as u32
    }

    /// Calculate hearing range
    pub fn hearing_range(&self) -> u32 {
        let base = 8 + (self.perception / 4);
        ((base as f32) * self.hearing_modifier) as u32
    }

    /// Check if enemy can hear noise at given distance
    pub fn can_hear(&self, noise: NoiseLevel, distance: u32) -> bool {
        let noise_radius = noise.detection_radius();
        let hearing = self.hearing_range();
        let effective_radius = noise_radius.min(hearing);
        distance <= effective_radius
    }

    /// Process hearing a noise
    pub fn hear_noise(&mut self, noise: NoiseLevel, source_pos: (usize, usize)) {
        if noise >= NoiseLevel::Quiet {
            self.state = self.state.on_noise_detected();
            self.investigation_point = Some(source_pos);
            self.decay_timer = 5 + (noise as u32 * 2);
        }
    }

    /// Process visual detection of player
    pub fn spot_player(&mut self, player_pos: (usize, usize)) {
        self.state = self.state.on_visual_detection();
        self.last_known_position = Some(player_pos);
        self.investigation_point = None;
        self.decay_timer = 10;
    }

    /// Enter combat state
    pub fn enter_combat(&mut self, player_pos: (usize, usize)) {
        self.state = AwarenessState::Combat;
        self.last_known_position = Some(player_pos);
        self.decay_timer = 15;
    }

    /// Check if player can be detected at given position
    pub fn check_detection(
        &self,
        player_stealth: &StealthState,
        distance: u32,
        has_line_of_sight: bool,
        player_has_invisibility: bool,
    ) -> bool {
        // Invisible players can't be visually detected
        if player_has_invisibility && !matches!(self.state, AwarenessState::Combat) {
            return false;
        }

        // Check if within detection range
        if distance > self.detection_range() {
            return false;
        }

        // Need line of sight for visual detection
        if !has_line_of_sight {
            return false;
        }

        // Calculate detection chance
        let base_chance = 50 + (self.perception as i32) - player_stealth.effective_stealth();
        let distance_penalty = (distance * 5) as i32;
        let detection_chance = (base_chance - distance_penalty).clamp(5, 95);

        // For deterministic checking, use threshold
        // In actual game, this would use RNG
        detection_chance > 50
    }

    /// Tick awareness decay
    pub fn tick(&mut self) {
        if self.decay_timer > 0 {
            self.decay_timer -= 1;
        } else if !matches!(self.state, AwarenessState::Unaware | AwarenessState::Combat) {
            self.state = self.state.decay();
            if matches!(self.state, AwarenessState::Unaware) {
                self.last_known_position = None;
                self.investigation_point = None;
            }
        }
    }

    /// Check if enemy can be backstabbed
    pub fn can_be_backstabbed(&self) -> bool {
        self.state.can_be_backstabbed()
    }

    /// Reset to unaware state
    pub fn reset(&mut self) {
        self.state = AwarenessState::Unaware;
        self.decay_timer = 0;
        self.last_known_position = None;
        self.investigation_point = None;
    }
}

/// Calculate backstab tier based on conditions
pub fn calculate_backstab_tier(
    awareness: &EnemyAwareness,
    player_stealth: &StealthState,
    enemy_hp_percent: f32,
    is_from_behind: bool,
    has_assassin_perk: bool,
) -> BackstabTier {
    // Can't backstab aware enemies
    if !awareness.can_be_backstabbed() {
        return BackstabTier::None;
    }

    // Calculate base tier from awareness
    let base_tier = match awareness.state {
        AwarenessState::Unaware => BackstabTier::Standard,
        AwarenessState::Suspicious => BackstabTier::Minor,
        _ => return BackstabTier::None,
    };

    // Check for critical conditions
    let is_critical = player_stealth.is_sneaking
        && is_from_behind
        && player_stealth.effective_stealth() >= 50
        && matches!(awareness.state, AwarenessState::Unaware);

    // Check for assassinate conditions
    let can_assassinate = has_assassin_perk
        && enemy_hp_percent <= 0.25
        && matches!(awareness.state, AwarenessState::Unaware)
        && player_stealth.effective_stealth() >= 75;

    if can_assassinate {
        BackstabTier::Assassinate
    } else if is_critical {
        BackstabTier::Critical
    } else {
        base_tier
    }
}

/// Calculate backstab damage
pub fn calculate_backstab_damage(
    base_damage: i32,
    tier: BackstabTier,
    stealth_skill: u32,
) -> i32 {
    let multiplier = tier.damage_multiplier();

    // Bonus damage from stealth skill (up to 50% more)
    let skill_bonus = 1.0 + (stealth_skill as f32 / 200.0);

    ((base_damage as f32) * multiplier * skill_bonus) as i32
}

/// Get terrain stealth modifier
pub fn terrain_stealth_modifier(tile: Tile) -> i32 {
    match tile {
        Tile::Grass => 15,        // Soft ground, quiet movement
        Tile::Sand => 5,          // Somewhat quiet
        Tile::Floor => 0,         // Normal
        Tile::Ice => -10,         // Slippery, hard to move quietly
        Tile::Water => -15,       // Splashing
        Tile::Lava => -20,        // Crackling, dangerous
        Tile::StairsDown | Tile::StairsUp => -5, // Metal stairs
        _ => 0,
    }
}

/// Get terrain noise modifier for movement
pub fn terrain_noise_modifier(tile: Tile) -> i32 {
    match tile {
        Tile::Grass => -1,  // Quieter
        Tile::Water => 2,   // Louder (splashing)
        Tile::Ice => 1,     // Slightly louder (crunching)
        Tile::Sand => 0,    // Normal
        _ => 0,
    }
}

/// Check if status effect reveals position
pub fn status_reveals_position(effect: StatusEffect) -> bool {
    matches!(
        effect,
        StatusEffect::Burn | StatusEffect::Poison // Visible effects
    )
}

/// Check if status effect aids stealth
pub fn status_aids_stealth(effect: StatusEffect) -> bool {
    matches!(effect, StatusEffect::Invisibility | StatusEffect::Haste)
}

/// Stealth-related game events
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum StealthEvent {
    /// Player entered stealth mode
    EnteredStealth,
    /// Player left stealth mode
    LeftStealth,
    /// Player was detected by an enemy
    Detected { enemy_name: String },
    /// Player performed a backstab
    Backstab { tier: BackstabTier, damage: i32 },
    /// Noise alerted enemies
    NoiseAlert { noise: NoiseLevel, enemies_alerted: u32 },
    /// Enemy became suspicious
    EnemySuspicious { enemy_name: String },
    /// Enemy lost track of player
    EnemyLostTrack { enemy_name: String },
}

impl StealthEvent {
    /// Get a message describing the event
    pub fn message(&self) -> String {
        match self {
            Self::EnteredStealth => "You begin sneaking...".to_string(),
            Self::LeftStealth => "You stop sneaking.".to_string(),
            Self::Detected { enemy_name } => format!("The {} spots you!", enemy_name),
            Self::Backstab { tier, damage } => {
                format!("{}! {} damage!", tier.name(), damage)
            }
            Self::NoiseAlert { noise, enemies_alerted } => {
                format!(
                    "Your {} noise alerts {} enemies!",
                    noise.name().to_lowercase(),
                    enemies_alerted
                )
            }
            Self::EnemySuspicious { enemy_name } => {
                format!("The {} heard something...", enemy_name)
            }
            Self::EnemyLostTrack { enemy_name } => {
                format!("The {} lost track of you.", enemy_name)
            }
        }
    }

    /// Get color index for the event message
    pub fn color_index(&self) -> u8 {
        match self {
            Self::EnteredStealth => 9,  // Cyan
            Self::LeftStealth => 1,     // Grey
            Self::Detected { .. } => 3, // Red
            Self::Backstab { tier, .. } => tier.color_index(),
            Self::NoiseAlert { .. } => 11, // Yellow
            Self::EnemySuspicious { .. } => 12, // DarkYellow
            Self::EnemyLostTrack { .. } => 5, // Green
        }
    }
}

/// Manager for tracking stealth state across multiple enemies
#[derive(Clone, Serialize, Deserialize, Debug, Default)]
pub struct StealthManager {
    /// Player's stealth state
    pub player_stealth: StealthState,
    /// Enemy awareness states (keyed by enemy index/id)
    pub enemy_awareness: HashMap<usize, EnemyAwareness>,
    /// Recent stealth events
    pub events: Vec<StealthEvent>,
    /// Global alert level (0-100)
    pub alert_level: u32,
}

impl StealthManager {
    /// Create a new stealth manager
    pub fn new() -> Self {
        Self {
            player_stealth: StealthState::new(),
            enemy_awareness: HashMap::new(),
            events: Vec::new(),
            alert_level: 0,
        }
    }

    /// Register an enemy for awareness tracking
    pub fn register_enemy(&mut self, id: usize, kind: EnemyKind) {
        self.enemy_awareness
            .insert(id, EnemyAwareness::for_enemy_kind(kind));
    }

    /// Remove an enemy from tracking
    pub fn remove_enemy(&mut self, id: usize) {
        self.enemy_awareness.remove(&id);
    }

    /// Process a noisy action
    pub fn process_action(&mut self, action: NoisyAction, player_pos: (usize, usize)) {
        let noise = self.player_stealth.make_noise(action);

        if noise >= NoiseLevel::Quiet {
            let mut alerted = 0;
            for awareness in self.enemy_awareness.values_mut() {
                if awareness.can_hear(noise, 5) {
                    // Simplified distance check
                    awareness.hear_noise(noise, player_pos);
                    alerted += 1;
                }
            }

            if alerted > 0 {
                self.events.push(StealthEvent::NoiseAlert {
                    noise,
                    enemies_alerted: alerted,
                });
                self.alert_level = (self.alert_level + alerted * 5).min(100);
            }
        }
    }

    /// Tick all awareness states
    pub fn tick(&mut self) {
        self.player_stealth.tick();

        for awareness in self.enemy_awareness.values_mut() {
            awareness.tick();
        }

        // Decay global alert level
        self.alert_level = self.alert_level.saturating_sub(1);
    }

    /// Get pending events and clear them
    pub fn drain_events(&mut self) -> Vec<StealthEvent> {
        std::mem::take(&mut self.events)
    }

    /// Check if any enemy is aware of the player
    pub fn any_enemy_aware(&self) -> bool {
        self.enemy_awareness
            .values()
            .any(|a| matches!(a.state, AwarenessState::Aware | AwarenessState::Combat))
    }

    /// Get count of enemies in each awareness state
    pub fn awareness_counts(&self) -> HashMap<AwarenessState, usize> {
        let mut counts = HashMap::new();
        for awareness in self.enemy_awareness.values() {
            *counts.entry(awareness.state).or_insert(0) += 1;
        }
        counts
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stealth_state_creation() {
        let state = StealthState::new();
        assert!(!state.is_sneaking);
        assert_eq!(state.stealth_skill, 10);
        assert_eq!(state.current_noise, NoiseLevel::Normal);
    }

    #[test]
    fn test_toggle_sneak() {
        let mut state = StealthState::new();
        assert!(state.toggle_sneak());
        assert!(state.is_sneaking);
        assert_eq!(state.current_noise, NoiseLevel::Silent);
        assert!(!state.toggle_sneak());
        assert!(!state.is_sneaking);
    }

    #[test]
    fn test_effective_stealth() {
        let mut state = StealthState::with_skill(50);
        let base = state.effective_stealth();

        state.start_sneak();
        let sneaking = state.effective_stealth();
        assert!(sneaking > base);

        state.light_level = LightLevel::Dark;
        let dark = state.effective_stealth();
        assert!(dark > sneaking);
    }

    #[test]
    fn test_noise_calculation() {
        let state = StealthState::new();
        assert_eq!(state.calculate_noise(NoisyAction::Sneak), NoiseLevel::Silent);
        assert_eq!(state.calculate_noise(NoisyAction::Walk), NoiseLevel::Quiet);
        assert_eq!(state.calculate_noise(NoisyAction::Combat), NoiseLevel::Loud);
    }

    #[test]
    fn test_awareness_decay() {
        let mut awareness = EnemyAwareness::new(15);
        awareness.state = AwarenessState::Alert;
        awareness.decay_timer = 0;

        awareness.tick();
        assert_eq!(awareness.state, AwarenessState::Searching);

        awareness.tick();
        assert_eq!(awareness.state, AwarenessState::Suspicious);
    }

    #[test]
    fn test_backstab_tier() {
        let awareness = EnemyAwareness::new(10);
        let mut stealth = StealthState::with_skill(80);
        stealth.start_sneak();

        let tier = calculate_backstab_tier(&awareness, &stealth, 1.0, true, false);
        assert_eq!(tier, BackstabTier::Critical);

        let aware = EnemyAwareness {
            state: AwarenessState::Aware,
            ..EnemyAwareness::new(10)
        };
        let tier = calculate_backstab_tier(&aware, &stealth, 1.0, true, false);
        assert_eq!(tier, BackstabTier::None);
    }

    #[test]
    fn test_backstab_damage() {
        let base_damage = 10;
        let standard = calculate_backstab_damage(base_damage, BackstabTier::Standard, 50);
        assert!(standard > base_damage);
        assert!(standard >= 20); // 2x multiplier minimum

        let critical = calculate_backstab_damage(base_damage, BackstabTier::Critical, 50);
        assert!(critical > standard);
    }

    #[test]
    fn test_terrain_modifiers() {
        assert!(terrain_stealth_modifier(Tile::Grass) > 0);
        assert!(terrain_stealth_modifier(Tile::Water) < 0);
        assert_eq!(terrain_stealth_modifier(Tile::Floor), 0);
    }

    #[test]
    fn test_enemy_awareness_for_kind() {
        let bat = EnemyAwareness::for_enemy_kind(EnemyKind::Bat);
        let zombie = EnemyAwareness::for_enemy_kind(EnemyKind::Zombie);

        // Bat should have better hearing
        assert!(bat.hearing_modifier > zombie.hearing_modifier);
        // Zombie should have worse perception
        assert!(bat.perception > zombie.perception);
    }

    #[test]
    fn test_stealth_manager() {
        let mut manager = StealthManager::new();
        manager.register_enemy(0, EnemyKind::Goblin);
        manager.register_enemy(1, EnemyKind::Orc);

        assert_eq!(manager.enemy_awareness.len(), 2);

        manager.player_stealth.start_sneak();
        assert!(manager.player_stealth.is_sneaking);

        manager.remove_enemy(0);
        assert_eq!(manager.enemy_awareness.len(), 1);
    }

    #[test]
    fn test_light_level_modifiers() {
        assert!(LightLevel::Dark.stealth_modifier() < LightLevel::Normal.stealth_modifier());
        assert!(LightLevel::Bright.stealth_modifier() > LightLevel::Normal.stealth_modifier());
    }
}
